/home/leonhard/anaconda3/envs/tactile_envs/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/leonhard/anaconda3/envs/tactile_envs/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/leonhard/workshop/test/M3L/trainDINO.py", line 264, in <module>
    main()
  File "/home/leonhard/workshop/test/M3L/trainDINO.py", line 231, in main
    model.learn(
  File "/home/leonhard/workshop/test/M3L/models/ppo_dino.py", line 451, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "/home/leonhard/anaconda3/envs/tactile_envs/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 313, in learn
    self.train()
  File "/home/leonhard/workshop/test/M3L/models/ppo_dino.py", line 321, in train
    self.dino_optimizer.zero_grad()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PPO_DINO' object has no attribute 'dino_optimizer'